### ISSUE TITLE
Protocol method when longPress started

### ISSUE THREAD

**Issue by thomasccpereira** [kunass2/BSTableViewReorder#2]
**Hi,**

How about protocol's method to inform delegate when longPress has started?

Amazing work! Thank you.
**Thomás**

**Comment by kunass2** [comment]
Do you really need it?

**Comment by thomasccpereira** [comment]
Yes, I need! My tableview is updated each minute, but I need this for invalidate the NSTimer while user is reordering some cells. Did you understand?

Thank you.
**Thomás Calmon**

**Comment by kunass2** [comment]
@thomascalmon  Ok, I have added a new protocol methods related to long press gesture recognizer:)

```
optional func tableViewDidStartLongPress(gestureRecognizer: UILongPressGestureRecognizer)
optional func tableViewDidEndLongPress(gestureRecognizer: UILongPressGestureRecognizer)
```

**Comment by thomasccpereira** [comment]
Thank you so much!
It worked great.

Cheers,
**Thomás Calmon**
